core/urls.py
from django.conf.urls import patterns, url
from .views import HomePageTemplateView

urlpatterns = patterns('',
                       url(r'^$', HomePageTemplateView.as_view(), name='home'))

mariochaves/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mariochaves.views.home', name='home'),
    # url(r'^mariochaves/', include('mariochaves.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    # App
    url(r'^', include('core.urls', namespace='core')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.views.generic.base import TemplateView


class HomePageTemplateView(TemplateView):
    template_name = 'home.html'

core/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Mário Chaves - {% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="keywords" content="site,mariochaves,mariochav.es,personal,pessoal,design,xsd,extreme,software">
    <meta name="description" content="Site pessoal do consultor Mário Chaves">
    <meta name="author" content="Mário Chaves <macndesign@gmail.com>">
    <!-- Google web fonts -->
    <link href='http://fonts.googleapis.com/css?family=Arvo:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <!-- Bootstrap -->
    <link href="{{ STATIC_URL }}css/bootstrap.min.css" rel="stylesheet" media="screen">
    <link href="{{ STATIC_URL }}css/bootstrap-responsive.min.css" rel="stylesheet" media="screen">
    <!-- Custom styles -->
    <link href="{{ STATIC_URL }}css/style.css" rel="stylesheet" media="screen">
    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="{{ STATIC_URL }}js/html5shiv.js"></script>
      <script src="{{ STATIC_URL }}js/html5shiv-printshiv.js"></script>
    <![endif]-->
    {% block extra_head %}{% endblock %}
</head>
<body>
<header>
    <div class="container">
        <a href="{% url 'core:home' %}" class="logo">mariochav.es</a>
    </div>
</header>
<div id="main">
    <div class="container">{% block content %}{% endblock %}</div>
</div>
<footer>
    <div class="container">Footer</div>
</footer>
<script src="{{ STATIC_URL }}js/jquery.min.js"></script>
<script src="{{ STATIC_URL }}js/bootstrap.min.js"></script>
{% block script %}{% endblock %}
</body>
</html>

core/templates/home.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
<h1>Home</h1>
<p>Home <i>page</i> content.</p>
<blockquote>
    Mussum ipsum cacilds, vidis litro abertis. Consetis adipiscings elitis. Pra lá , depois divoltis porris, paradis. Paisis, filhis, espiritis santis. Mé faiz elementum girarzis, nisi eros vermeio, in elementis mé pra quem é amistosis quis leo. Manduma pindureta quium dia nois paga. Sapien in monti palavris qui num significa nadis i pareci latim. Interessantiss quisso pudia ce receita de bolis, mais bolis eu num gostis.
</blockquote>
{% endblock %}